import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import ArrowDownwardIcon from '@mui/icons-material/ArrowDownward';
import Profile from './profile/profile';
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <h1>Portfolio </h1>
        <h1>Nahuel Sánchez</h1>
        <div className={styles.bar}>
          <p>About Me</p>
          <ArrowDownwardIcon />
        </div>
          <Profile />
        <div className={styles.bar}>
          <p>Works</p>
          <ArrowDownwardIcon />
        </div>
        <div className={styles.bar}>
          <p>Skills</p>
          <ArrowDownwardIcon />
        </div>
        <div className={styles.bar}>
          <p>Contact</p>
          <ArrowDownwardIcon />
        </div>

      </div>
    </>
  )
}
