import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Profile from './profile/profile';
import Proyect from './proyect';
import { ParallaxProvider } from 'react-scroll-parallax';
import Contact from './contact';
export default function Home() {
  return (
    <>
      <ParallaxProvider>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className={styles.container}>


          <h1>Portfolio </h1>
          <h1>Nahuel Sánchez</h1>

          <div className={styles.bar}>
            <p>About Me</p>
          </div>
          <Profile />
          <div className={styles.bar}>
            <p>Works</p>
          </div>
          <Proyect />
          
    {/*       <div className={styles.bar}>
            <p>Skills</p>
          </div>
          <Skill /> */}
          <div className={styles.bar}>
            <p>Contact</p>
          </div>
          <Contact />
        </div>
      </ParallaxProvider>
    </>
  )
}
